import Foundation

/// A representation of a generated mini‑app.
///
/// Each mini‑app consists of multiple source files that the Gemini API returned.
/// The files are stored on disk in a folder whose name is the mini‑app’s UUID.
struct MiniApp: Identifiable, Codable, Equatable {
    var id: UUID
    var name: String
    var created: Date
    var files: [MiniFile]

    /// Returns the path on disk where this mini‑app’s folder lives.
    func folderURL() throws -> URL {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
        return docs.appendingPathComponent("miniapps").appendingPathComponent(id.uuidString)
    }
}

/// A representation of a single source file generated by the LLM.
struct MiniFile: Codable, Equatable, Identifiable {
    var id: UUID = UUID()
    var name: String
    var content: String
}
